version: '3'
services:
 bitwarden:
  image: mprasil/bitwarden:alpine
  restart: always
  volumes:
      - ./bw-data/:/data/
  environment:
   WEBSOCKET_ENABLED: "true"
   SIGNUPS_ALLOWED: "false"
   LOG_FILE: "/data/bitwarden.log"
  ports:
      - 3080:80
      - 3012:3012
